In [ ]:
import pandas as pd

data = (

      { "name" : "meet", "marks" : 350 },
      { "name" : "raj", "marks" : 400 },
      { "name" : "yash", "marks" : 500},
      { "name" : "bhima", "marks" : 450},
      { "name" : "meera", "marks" : 650},
      { "name" : "mansi", "marks" : 700},
      { "name" : "vivek", "marks" : 450},
      { "name" : "raju", "marks" : 470},
      { "name" : "jagu", "marks" : 640},
      { "name" : "chandu", "marks" : 480},
)

df = pd.DataFrame(data)
print(df)

     name  marks
0    meet    350
1     raj    400
2    yash    500
3   bhima    450
4   meera    650
5   mansi    700
6   vivek    450
7    raju    470
8    jagu    640
9  chandu    480

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_json("/content/sample_data/anscombe.json")
df

   Series   X      Y
0       I  10   8.04
1       I   8   6.95
2       I  13   7.58
3       I   9   8.81
4       I  11   8.33
5       I  14   9.96
6       I   6   7.24
7       I   4   4.26
8       I  12  10.84
9       I   7   4.81
10      I   5   5.68
11     II  10   9.14
12     II   8   8.14
13     II  13   8.74
14     II   9   8.77
15     II  11   9.26
16     II  14   8.10
17     II   6   6.13
18     II   4   3.10
19     II  12   9.13
20     II   7   7.26
21     II   5   4.74
22    III  10   7.46
23    III   8   6.77
24    III  13  12.74
25    III   9   7.11
26    III  11   7.81
27    III  14   8.84
28    III   6   6.08
29    III   4   5.39
30    III  12   8.15
31    III   7   6.42
32    III   5   5.73
33     IV   8   6.58
34     IV   8   5.76
35     IV   8   7.71
36     IV   8   8.84
37     IV   8   8.47
38     IV   8   7.04
39     IV   8   5.25
40     IV  19  12.50
41     IV   8   5.56
42     IV   8   7.91
43     IV   8   6.89

In [ ]:
df_1 = pd.DataFrame({'ID' : [1,2,3,4,5,],
                     'class' : [9,10,11,12,13]})

df_1

   ID  class
0   1      9
1   2     10
2   3     11
3   4     12
4   5     13

In [ ]:
df_2 = pd.DataFrame({'ID' : [6,7,8,9,10],
                     'name' : [14,15,16,17,18]})
df_2

   ID  name
0   6    14
1   7    15
2   8    16
3   9    17
4  10    18

In [ ]:
merge =pd.merge(df_1,df_2,on = 'ID')
merge

Empty DataFrame
Columns: [ID, class, name]
Index: []

In [ ]:
merge =pd.merge(df_1,df_2,on = 'ID' , how = 'inner')
merge

Empty DataFrame
Columns: [ID, class, name]
Index: []

In [ ]:
merge =pd.merge(df_1,df_2,on = 'ID' , how = 'left')
merge

   ID  class  name
0   1      9   NaN
1   2     10   NaN
2   3     11   NaN
3   4     12   NaN
4   5     13   NaN

In [ ]:
merge =pd.merge(df_1,df_2,on = 'ID' , how = 'right')
merge

   ID  class  name
0   6    NaN    14
1   7    NaN    15
2   8    NaN    16
3   9    NaN    17
4  10    NaN    18

In [ ]:
merge =pd.merge(df_1,df_2,on = 'ID' , how = 'outer')
merge

   ID  class  name
0   1    9.0   NaN
1   2   10.0   NaN
2   3   11.0   NaN
3   4   12.0   NaN
4   5   13.0   NaN
5   6    NaN  14.0
6   7    NaN  15.0
7   8    NaN  16.0
8   9    NaN  17.0
9  10    NaN  18.0

In [ ]:
merge =pd.merge(df_1,df_2,on = 'ID' , how = 'outer', indicator = True)
merge

   ID  class  name      _merge
0   1    9.0   NaN   left_only
1   2   10.0   NaN   left_only
2   3   11.0   NaN   left_only
3   4   12.0   NaN   left_only
4   5   13.0   NaN   left_only
5   6    NaN  14.0  right_only
6   7    NaN  15.0  right_only
7   8    NaN  16.0  right_only
8   9    NaN  17.0  right_only
9  10    NaN  18.0  right_only

In [ ]:
merge =pd.merge(df_1,df_2,on = 'ID' , how = 'inner', indicator = True)
merge

Empty DataFrame
Columns: [ID, class, name, _merge]
Index: []

In [ ]:
merge =pd.merge(df_1,df_2,on = 'ID' , how = 'left', indicator = True)
merge

   ID  class  name     _merge
0   1      9   NaN  left_only
1   2     10   NaN  left_only
2   3     11   NaN  left_only
3   4     12   NaN  left_only
4   5     13   NaN  left_only

In [ ]:
merge =pd.merge(df_1,df_2,on = 'ID' , how = 'right', indicator = True)
merge

   ID  class  name      _merge
0   6    NaN    14  right_only
1   7    NaN    15  right_only
2   8    NaN    16  right_only
3   9    NaN    17  right_only
4  10    NaN    18  right_only

In [ ]:
merge =pd.merge(df_1,df_2,on = 'ID' , how = 'outer', indicator = True)
merge

   ID  class  name      _merge
0   1    9.0   NaN   left_only
1   2   10.0   NaN   left_only
2   3   11.0   NaN   left_only
3   4   12.0   NaN   left_only
4   5   13.0   NaN   left_only
5   6    NaN  14.0  right_only
6   7    NaN  15.0  right_only
7   8    NaN  16.0  right_only
8   9    NaN  17.0  right_only
9  10    NaN  18.0  right_only

In [ ]:
df1 = pd.DataFrame({ 'User_id' : [101,102,103],
                  'User_name' : ["raj", "mrrt", "meera"]})
df1

   User_id User_name
0      101       raj
1      102      mrrt
2      103     meera

In [ ]:
df2 = pd.DataFrame({
    'User_id' : [101,102,103],
    'city' : ["raj", "jun", "ahe"]
})
df2

   User_id city
0      101  raj
1      102  jun
2      103  ahe

In [ ]:
index = pd.merge(df1,df2, left_index = True, right_index  = True )
index

   User_id_x User_name  User_id_y city
0        101       raj        101  raj
1        102      mrrt        102  jun
2        103     meera        103  ahe

In [ ]:
df11 = pd.DataFrame({ 'User_id' : [101,102,103],
                  'User_name' : ["raj", "mrrt", "meera"]}, index = [11,22,33])
df11

   User_id User_name
0      101       raj
1      102      mrrt
2      103     meera

In [ ]:
df22 = pd.DataFrame({
    'User_id' : [101,102,103],
    'city' : ["raj", "jun", "ahe"]
}, index = [11,22,33])
df22

    User_id city
11      101  raj
22      102  jun
33      103  ahe

In [ ]:
data = {

        'age' : [23,34,56,np.nan,45,22,np.nan],
        'name' : ["meet", "raj", "yash", "bhima", "meera", "mansi", "vivek"],
        'city' : ['raj', 'jun', 'ahe', 'jam', 'por', 'kes', 'sur']
}
df = pd.DataFrame(data)
print("orignal data \n")
df

orignal data

    age   name city
0  23.0   meet  raj
1  34.0    raj  jun
2  56.0   yash  ahe
3   NaN  bhima  jam
4  45.0  meera  por
5  22.0  mansi  kes
6   NaN  vivek  sur

In [ ]:
print(df.isnull())

     age   name   city
0  False  False  False
1  False  False  False
2  False  False  False
3   True  False  False
4  False  False  False
5  False  False  False
6   True  False  False

In [ ]:
print(df.isnull().sum())

age     2
name    0
city    0
dtype: int64

In [ ]:
print(df.notnull())

     age  name  city
0   True  True  True
1   True  True  True
2   True  True  True
3  False  True  True
4   True  True  True
5   True  True  True
6  False  True  True

In [ ]:
print(df.dropna())

    age   name city
0  23.0   meet  raj
1  34.0    raj  jun
2  56.0   yash  ahe
4  45.0  meera  por
5  22.0  mansi  kes

In [ ]:
print(df.dropna(axis=1))

    name city
0   meet  raj
1    raj  jun
2   yash  ahe
3  bhima  jam
4  meera  por
5  mansi  kes
6  vivek  sur

In [ ]:
print(df.dropna(subset=['age']))

    age   name city
0  23.0   meet  raj
1  34.0    raj  jun
2  56.0   yash  ahe
4  45.0  meera  por
5  22.0  mansi  kes

In [ ]:
print(df.fillna(0))

    age   name city
0  23.0   meet  raj
1  34.0    raj  jun
2  56.0   yash  ahe
3   0.0  bhima  jam
4  45.0  meera  por
5  22.0  mansi  kes
6   0.0  vivek  sur

In [ ]:
df['age'] = df.['age'].fillna(df['age'].mean())

In [ ]:
df['city'] = df.['city'].fillna(df['city'].mean()[0])