In [5]:
import pandas as pd
df = pd.read_csv(r"/content/student_results.xls")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [ ]:
#location and I loc


import pandas as pd

In [6]:
df = pd.read_csv(r"/content/student_results.xls")
df

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [8]:
df.loc[:]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60
3,1004,11,0,10,1,5,45
4,1005,11,4,7,2,0,75
5,1006,11,10,7,0,0,96
6,1007,12,4,6,0,0,80
7,1008,12,10,6,2,0,90
8,1009,12,2,8,2,4,60
9,1010,12,6,9,1,0,85

In [9]:
df.loc[0]

Student ID                1001
Class                       10
Study hrs                    2
Sleeping hrs                 9
Social Media usage hrs       3
Mobile Games hrs             5
Percantege                  50
Name: 0, dtype: int64

In [10]:
df.loc[1]

Student ID                1002
Class                       10
Study hrs                    6
Sleeping hrs                 8
Social Media usage hrs       2
Mobile Games hrs             0
Percantege                  80
Name: 1, dtype: int64

In [12]:
df.loc[[0,1]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80

In [23]:
df.loc[4,'Class']

np.int64(11)

In [18]:
df.loc[0:2, 'Percantege']

0    50
1    80
2    60
Name: Percantege, dtype: int64

In [27]:
df.loc[df['Class'] < 11]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50
1,1002,10,6,8,2,0,80
2,1003,10,3,8,2,4,60

In [22]:
df.loc[df['Class'] < 11, 'Percantege']

0    50
1    80
2    60
Name: Percantege, dtype: int64

In [26]:
df.loc[df['Class'] < 11, 'Study hrs']

0    2
1    6
2    3
Name: Study hrs, dtype: int64

In [25]:
df.iloc[[0]]

,Student ID,Class,Study hrs,Sleeping hrs,Social Media usage hrs,Mobile Games hrs,Percantege
0,1001,10,2,9,3,5,50

In [28]:
df.iloc[:,0]

0    1001
1    1002
2    1003
3    1004
4    1005
5    1006
6    1007
7    1008
8    1009
9    1010
Name: Student ID, dtype: int64

In [29]:
df.iloc[:,1]

0    10
1    10
2    10
3    11
4    11
5    11
6    12
7    12
8    12
9    12
Name: Class, dtype: int64